### ISSUE TITLE
Unable To Make DAI Offer

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3183] opened 2019-09-03 17:40 UTC
@joshfraser reported that a user was attempting to make an offer on [this listing](https://shoporigin.com/#/listing/1-000-2912) and was stuck on the "approve currency conversion" step. 😕

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment] 2019-09-03 22:33
Do we have any extra information that could help us troubleshooting this issue ?
- ETH address of the buyer
- Android vs iOS
- Time of occurrence

**Comment by micahalcorn** [comment] 2019-09-04 22:43
Here is a MetaMask trace from one of my failed offers 🙁
```
tx error Error: Transaction ran out of gas. Please provide more gas:
{
  "blockHash": "0xb544dc42cd5b4b9f8a394531a99ba9edcc4d0846a7e9c9d92da8103159d98003",
  "blockNumber": 8486309,
  "contractAddress": null,
  "cumulativeGasUsed": 7955050,
  "from": "0xbfdd843382b36ffbacd00b190de6cb85ff840118",
  "gasUsed": 295170,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xe427b7e4d1875b4900a38451961a8e958fe20624",
  "transactionHash": "0xdfc5bd6435d27578840f98bf320d0834a6157ec3c18666bee37092c81a0df99e",
  "transactionIndex": 94,
  "events": {}
}
    at index.js:370
```

**Comment by micahalcorn** [comment] 2019-09-04 22:48
Some decoded (unrelated) transaction info from @DanielVF 😳

![makeoffer](https://user-images.githubusercontent.com/273937/64298686-4cc47e80-cf2b-11e9-82c9-ac135c586d9f.png)

**Comment by franckc** [comment] 2019-09-04 22:51
Here are a a couple examples of transactions that failed:
https://www.etherchain.org/tx/1b655990ebd322383352c33c578c31603f20d95cf69564cf8e816601532c7484
https://etherscan.io/tx/0x5645eed56c748caeb314d8aea1417cfe9ae8baf9634739258ed1567c002c8e54

**Comment by mikeshultz** [comment] 2019-09-04 23:04
I think @DanielVF was already on this track, but for record keeping, it appears to be reverting here:

https://github.com/OriginProtocol/origin/blob/608090024f7e8559909882d5bb05a391622c6529/packages/contracts/contracts/identity/IdentityProxy.s#L202

**Comment by mikeshultz** [comment] 2019-09-04 23:46
The raised gas limit worked for me. 

https://etherscan.io/tx/0x86a43785625dd17e2b682cbfa063db61522228198ef24b29aed34170f88dc26d

- limit: `385,000`
- used: `296400`

Extra interesting considering it looks like it didn't use more than the previous limit.  Could have something to do with how `DELEGATECALL` behaves.  Could be [related to his](https://ethereum.stackexchange.com/a/23592)?

**Comment by franckc** [comment] 2019-09-05 03:38
Another interesting data point. Earlier in the day, before we bumped the gas limit to 350k for makeOffer, @micahalcorn successfully made an offer on a DAI listing using Coinbase wallet. Here is the tx:
https://etherscan.io/tx/0xd3e08c4e78c9990b261080df7a49575e790b614f97b0a0c6033b06b8e8944856
It shows the gasLimit on that tx was set to 1M ! And 508,685 gas were used. So it looks like Coinbase wallet does not not respect the gasLimit passed by the DApp...

**Comment by franckc** [comment] 2019-09-05 03:43
For the record we deployed #3204 to prod at about 4:30pm
Since then we haven't seen any new occurrence of this issue.

**Comment by franckc** [comment] 2019-09-05 03:48
Also, a theory to explain from @mikeshultz to explain the root cause of this issue is that due to #3004 , we may now use extra gas to refund the excess ETH to the proxy contract.

**Comment by franckc** [comment] 2019-09-05 20:22
We haven't run into this OOG issue since we bumped up gas limit so closing.

@DanielVF if you could still confirm the theory that the gas limit increase was due to the refund of excess ETH, would be great...

**Closed** 2019-09-05 20:22 UTC
Labels: P0, bug, dapp, help wanted, ui/ux

**Comment by DanielVF** [comment] 2019-09-06 19:50
@mikeshultz You are right about the gas being reserved from the calls. That does mean that we need to send more gas then we use. We do a delegate call right away into our master proxy code, then we are later going into make offer with a pile of gas.

**Comment by DanielVF** [comment] 2019-09-06 20:02
@franckc I believe @mikeshultz is right about the root cause.

**Comment by DanielVF** [comment] 2019-09-06 20:03
> @micahalcorn successfully made an offer on a DAI listing using Coinbase wallet. Here is the tx:
> https://etherscan.io/tx/0xd3e08c4e78c9990b261080df7a49575e790b614f97b0a0c6033b06b8e8944856
> It shows the gasLimit on that tx was set to 1M ! And 508,685 gas were used. So it looks like Coinbase wallet does not not respect the gasLimit passed by the DApp...

@franckc This is because a new proxy was created along with that transaction. I think we override the gas price to a million when we do that?

**Comment by franckc** [comment] 2019-09-06 22:12
@DanielVF Ah yes you are right, in case a proxy gets created, we override gas limit to 1M
https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/mutations/_txHelper.js#L170

Thanks for confirming the root cause of this issue !
