### ISSUE TITLE
Translation duplicates / string identifiers

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#760] opened 2018-10-16 14:58 UTC
(@micahalcorn this may be something to cover in a bigger discussion of localization issues, but just want to get this down.)

Looking through `all-messages.json` it seems we are being overly prolific with string identifiers, making the identifiers unique to the specific page/component. E.g. the word "continue" will almost certainly be translated the same in all cases. So there is no reason to have it broken out into multiple strings with identifiers `AttestationSuccess.continue`, `EditProfile.continue`, `Profile.continue`, `VerifyAirbnb.continue`, `VerifyEmail.continue`, `VerifyFacebook.continue`, and on and on. Having the same phrase over and over introduces risk that translator may choose an alternate forms for one of the occurrences. In the rare case where the same English word needs different handling in another language, we can then break it apart into multiple identifiers. 

My rough thought is that for any non-sentence we just use the camelCase version of the string as the identifier. E.g. "Verify email address"-->`verifyEmailAddress` and longer ones get reduced to a summary, e.g. 
"Go to Airbnb website, edit your profile and paste the following text into profile description." --> `enterCodeIntoAirbnb`

**Comment by micahalcorn** [comment] 2018-10-16 15:29
Yes, this is part of what @crazybuster and I would like to solve across the various monorepo directories as well. I seem to recall there also being some kind of hiccup with needing unique component-specific identifiers throughout the DApp with our current implementation per @jordajm.

**Comment by jordajm** [comment] 2018-10-16 16:02
A few thoughts on this @wanderingstan and @micahalcorn ...

- Yes, I was surprised by `react-intl` not allowing duplicated IDs across components

- However, it's a best practice for a reason, and I tend to agree with it because when I tried to reuse message IDs across components, it got very confusing trying to keep track of the global IDs as in, "wait, do I have this message already defined globally or is this something I need to create a new ID for"... I even started a spreadsheet of global IDs to try to keep track of them and it got super messy and time consuming - and would be more-so if there were more devs involved.

- Crowdin has a "translation memory" feature that auto-translates identical strings when a translator translates one string that has duplicates, and they can override that memory-based translation as needed

- So, it's really just the bloat in the auto-generated JSON files that we're talking about I think, which I understand is a long-term concern but I'm not sure how much of a priority it really should be... ?

- There's also an automation tool that we could implement so we never have to think about message IDs - I'd be a fan of this approach:
https://www.npmjs.com/package/babel-plugin-react-intl-auto

**Comment by micahalcorn** [comment] 2018-10-16 16:40
The issue that Yu Pan and I are concerned about is having the same string translated differently across -dapp, -js, -tbd-notifications-thing, etc. Now that they are all under the same repo, hopefully CrowdIn will save us from having conflicting translations across projects @jordajm?

**Comment by jordajm** [comment] 2018-10-16 16:55
Yes, I think Crowdin can help us prevent different translations of the same strings across the repos. I just confirmed that we have enabled the Crowdin feature which lets the translation memory be shared across projects:
https://crowdin.com/resources#translation-memory

**Comment by micahalcorn** [comment] 2019-01-08 20:15
@BrunoBernardino please see above and let us know if you have any thoughts about a shared library of string ids that can be used across modules (-dapp, -notifications, -mobile, etc).

**Comment by BrunoBernardino** [comment] 2019-01-09 08:03
[babel-plugin-react-intl-auto](https://www.npmjs.com/package/babel-plugin-react-intl-auto) looks pretty sweet, since we can still define manual IDs for common words!

For the shared library off those common words, I'm thinking we create a main `commonWords.js` file, like:

```js
// commonWords.js
const commonWords = {
  continue: 'Continue',
  verifyEmailAddress: 'verify Email Address',
}

// This would help prevent setting the id twice
const messages = Object.keys(words).map((id) => ({ id, defaultMessage: words[id] }))

export default defineMessages(commonWords)
```

And then we'd just include that when we needed the common words. For everything else, we'd just keep using `react-intl` "as usual" (which, with the plugin, will create the auto id).

```js
// Button.js
import React from 'react'
import { FormattedMessage } from 'react-intl'

import commonMessages from './commonMessages'

export default () => (
  <div>
    <p>
      <FormattedMessage
        description='Greeting to welcome the user to the dapp'
        defaultMessage='Hello, {name}!'
        values={{
          name: 'John'
        }}
      />
    </p>
    <button>
      <FormattedMessage {...commonMessages.continue} />
    <button>
)
```

This still gives us the flexibility of creating specific ids for common words (by using the default format instead of the commonWords).

**Comment by wanderingstan** [comment] 2019-01-09 16:12
Funny to say this as the guy that opened the issue, but I think @jordajm makes a solid point in explaining the reasoning behind `react-intl` enforcing uniqueness, and showing that the translation tool can be the layer at which we worry about duplicates.

As this [SO answer](https://stackoverflow.com/a/37416102) indicates, we could possibly make a "commonly used strings" file if we really wanted.

And this all may be moot: With the move to GraphQL, we might consider moving to the newly released [FBT Framework](https://facebookincubator.github.io/fbt/) from Facebook, which fits hand-in-glove with react and probably will get more support going forward than yahoo gives to `react-intl`. (Need to investigate if/how this would work with Crowdin.)

But, given our project is still relatively small in scope, and we aren't having any problems, I think this is a can we can safely kick down the road.

**Comment by micahalcorn** [comment] 2019-04-04 21:46
Closing this since fbt 🌐

**Closed by micahalcorn** 2019-04-04 21:46 UTC
Labels: dapp, discussion, enhancement, javascript, mobile, notifications, translations
