### ISSUE TITLE
Mobile Confirmation for Created Listing

### ISSUE THREAD

**Issue by Natasha08** [OriginProtocol/origin#829] opened 2018-10-25 15:11 UTC
Note: This issue was created based on testing in Coinbase Wallet (previously Toshi).

The DApp said the listing was created. There is a bug when trying to view it on My Listings or in Browse: `Couldn’t decode address from ABI: 0x`

Potentially caused by:
- Something is being malformed as it’s being written to the contract
- Could also be a Coinbase issue? Although in this case our DApp thinks the transaction was completed.

**Comment by micahalcorn** [comment] 2018-11-15 17:22
Duplicate of https://github.com/OriginProtocol/origin/issues/799

**Closed by micahalcorn** 2018-11-15 17:22 UTC
Labels: bug, dapp, javascript, mobile, p1
