### ISSUE TITLE
Growth banner layout on small mobile devices

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2072] opened 2019-04-19 04:26 UTC
Button layout is a bit funky.

![Screenshot_1555647890](https://user-images.githubusercontent.com/489202/56405279-c41cad00-62bf-11e9-8436-714a9d738871.png)

**Comment by micahalcorn** [comment] 2019-04-19 04:31
Duplicate of https://github.com/OriginProtocol/origin/issues/1928 🙂

**Closed by micahalcorn** 2019-04-19 04:31 UTC
Labels: P2, growth, mobile
