### ISSUE TITLE
[Mobile] Origin Rewards terms signing modal spins forever

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2176] opened 2019-05-01 18:20 UTC
Repro steps:
 - Open Origin mobile app with an account that hasn't enrolled in Origin Rewards yet
 - Go to webview
 - Tap on hamburger menu and then tap on "Earn Tokens"
=> User is asked to sign the terms and then a spinning modal appears and stays forever.

**Comment by sparrowDom** [comment] 2019-05-03 15:00
This has been fixed by @tomlinton in https://github.com/OriginProtocol/origin/pull/2146 . Tested this on `OriginWallet` and it works nicely. Though the solution does break the rewards signature working on Coinbase wallet. Coinbase is of a lower priority but we should still support it. 

The problem is that Coinbase and Origin both use react native and we check for existence of react native when choosing a signature function. 

@tomlinton have briefly inspected OriginWallet codebase but couldn't find it... is there any way to determine (on window object perhaps) that the Dapp is running hosted in OriginWallet? (instead of other  React native wallets)

**Comment by sparrowDom** [comment] 2019-05-03 20:53
Actually after some more testing solution from  @tomlinton didn't break anything. On May 2nd CoinBase wallet has released an updated version of their Android app an broke the behaviour. On an iPhone where I haven't updated the Coinbase Wallet this still works as it should.

**Closed by sparrowDom** 2019-05-03 20:53 UTC
Labels: P1, bug, growth, identity, mobile, ui/ux
