### ISSUE TITLE
Stuck on Loading Payment Method

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#4039] opened 2019-11-21 21:15 UTC
With our mobile app, I created a new wallet and attempted to purchase [this listing](https://shoporigin.com/#/listing/1-000-3145). I don't see anything in the DApp console nor in Sentry.

![D75F96BF-15FC-4AA2-9509-D05AE9DD2166](https://user-images.githubusercontent.com/273937/69377153-853d4400-0c60-11ea-9457-d498d2b6639e.png)

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mahamat** [comment] 2019-11-27 18:41
Hey @micahalcorn , debugging this bug, it happens on desktop when site is not connected on Metamask, or when i do not connect to Metamask and chose Cancel button. For example: 
https://shoporigin.com/#/listing/1-000-2832 and https://shoporigin.com/#/listing/1-000-2832 are stuck in `Loading` state. 

Debugging the code, it seems it is using this query, ```export default gql`
  query WalletStatus {
    web3 {
      metaMaskAccount {
        id
      }
    }
    messaging(id: "defaultAccount") {
      id
      pubKey
      pubSig
      enabled
      isKeysLoading
      synced
      syncProgress
    }
  }
```` and when metamask is not connected, `messaging` is null, thus `const isKeysLoading = get(data, 'messaging.isKeysLoading', true)` gets default true value (prop messagingKeysLoading), and ```if (
    messagingStatusLoading ||
    identityLoading ||
    walletLoading ||
    messagingKeysLoading
  ) {
    return (
      <button
        className={className}
        children={<fbt desc="Loading...">Loading...</fbt>}
        disabled={true}
      />
    )
  }``` purchase button is stuck in Loading state. 

So, in your case, is wallet connected and still this bug occurs ? Thanks.

**Comment by micahalcorn** [comment] 2019-11-29 10:23
Yes @mahamat, there isn't really any concept of "connecting" the wallet in our app. There is no EIP 1102 privacy, and the wallet signs an authentication token prior to reaching this screen.

I just tried to reproduce it though and I wasn't able to. 😕

**Comment by sparrowDom** [comment] 2020-01-10 18:08
So there are 2 problems here that cause this: 
- User is on desktop and not logged in to Metamask (like pointed out by @mahamat)
- User has on a previous listing selected a purchase method (let say OGN) and then opens another listing that doesn't offer that purchase method.

Fixes for that here: https://github.com/OriginProtocol/origin/pull/4249

**Comment by micahalcorn** [comment] 2020-01-16 17:50
This is currently happening at https://shoporigin.com/#/listing/1-000-140/payment and not producing any errors in Sentry. 😕

**Comment by sparrowDom** [comment] 2020-01-17 09:55
Interesting there seems to be another issue preventing the purchase button. The reason seems to be that for some reason on some listings the accepted seller's payment methods don't load up. Will investigate why

**Comment by sparrowDom** [comment] 2020-01-17 11:22
@micahalcorn have prepared a fix for this: https://github.com/OriginProtocol/origin/pull/4288

The problem is that some listings are wrongly stored [see Json](https://pastebin.com/6nH5aqh9) as if they accept no payment methods at all. The fix (if you agree is ok and will not enrage sellers) is that we add an ETH payment option on those listings.

**Comment by micahalcorn** [comment] 2020-01-18 09:28
Thanks @sparrowDom 😕 Do we know how they are getting wrongly stored in the first place?

**Closed** 2020-01-18 09:29 UTC
Labels: P1, bug, dapp, javascript, transaction flow

**Comment by sparrowDom** [comment] 2020-01-18 13:25
@micahalcorn I tried to reproduce it on production. But with new listing creation or editing a listing I didn't have any success.
