### ISSUE TITLE
$0 listings that accept DAI and ETH as payment still attempt DAI swap

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3167] opened 2019-09-02 08:32 UTC
Instead of just using ETH the DApp appears to be attempting to send a DAI swap transaction via the relayer, resulting in gas costs.

**Comment by micahalcorn** [comment] 2019-09-02 16:43
Duplicate of https://github.com/OriginProtocol/origin/issues/2651 🙁

**Closed by micahalcorn** 2019-09-02 16:43 UTC
Labels: P2, dapp, duplicate
