### ISSUE TITLE
Making Offer on Android fails

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3411] opened 2019-09-16 20:44 UTC
When @kayyoo23 is trying to make an offer from her Android she consistently gets stuck on [this screen]("https://drive.google.com/a/originprotocol.com/file/d/1lIeHwwZ-JqbBCRcGn5XZqUot9StgUS9V/view?usp=sharing").  

These are the errors reported by Sentry from her device: [error 1](https://sentry.io/organizations/origin-protocol/issues/1098412085/events/6c567745306f42ee99456354c54c19bf/?project=1402589) [error 2](https://sentry.io/organizations/origin-protocol/issues/1098412085/events/1607309113a24eb880cd26f7690c58d4/?project=1402589) [error 3](https://sentry.io/organizations/origin-protocol/issues/1083668175/events/77aca833a85e4359966f7698d7a68bf8/?project=1402589) [error 4](https://sentry.io/organizations/origin-protocol/issues/1020146212/events/81bd53e53a4c44279fe7c9ec10e7559d/?project=1402589)

**Comment by mikeshultz** [comment] 2019-09-16 21:44
I don't understand why it's requesting a transaction receipt when no transaction has even been sent.

Account: https://etherscan.io/address/0x0bB2C6478677aCbAd673e1D55FD26B0C06Ae2e18
Proxy: https://etherscan.io/address/0x2cad506fa67291ce479eca86d6ec5ebfa5ff7336

**Comment by mikeshultz** [comment] 2019-09-16 21:49
This issue encompasses #3275, #3410

I think `Invalid params` is perhaps at the core of this one.

**Comment by franckc** [comment] 2019-09-16 21:54
I watched @kayyoo23 try to make an offer on a **different** listing. This time she got stuck on the confirmation page. The blue button for confirming had a spinner and never became clickable.

![Screenshot_20190916-144941_Origin](https://user-images.githubusercontent.com/945910/64996097-dc561f80-d891-11e9-81c3-6098322d0b03.jpg)

**Comment by mikeshultz** [comment] 2019-09-16 21:54
Actually, I'm gonna say it's the messaging bug (shipping address) broken out in #3410.

**Comment by tomlinton** [comment] 2019-09-16 21:57
This would happen if [this](https://github.com/OriginProtocol/origin/blob/22f30f44ad8dc2d51179a2bd5ef0b579250fc94b/mobile/src/components/origin-web3view.js#L82) resolved but failed to have sent this transaction. If it errored the app should crash and we should see something reported in Sentry for `origin-mobile`. It seems like it is resolving but never sending the transaction correctly. I wonder if it is something with Alchemy. But that doesn't make sense if it is just limited to that one device.

**Comment by tomlinton** [comment] 2019-09-17 02:08
I don't think this is Android (or mobile) specific. I think its more likely an issue with Alchemy.

**Comment by mikeshultz** [comment] 2019-09-17 16:42
@tomlinton could this be caused by it getting garbage for `transaction`/`msgData.data`?

**Comment by tomlinton** [comment] 2019-09-18 10:07
I think that is unlikely as all of the data in that screenshot above is parsed from the transaction data in `msgData.data`.

**Comment by mikeshultz** [comment] 2019-09-18 19:15
ok, so, had a look at [the ethers.js docs](https://docs.ethers.io/ethers.js/html/api-wallet.html#blockchain-operations):

> Sends the transaction (see Transaction Requests) to the network and returns a Promise that resolves to a Transaction Response. Any properties that are not provided will be populated from the network.

The [transaction response object](https://docs.ethers.io/ethers.js/html/api-providers.html#transaction-response) appears to be a regular old transaction object and it doesn't appear to block for mining or anything.

I have no idea what the behavior would be with some of the Alchemy behavior.  For instance, what does Ethers.js do upon a 429 rate limiting behavior?  This was a big part of the reasoning for building our own web3.js provider.  And I'm not really sure how we should approach this either, since the mobile app doesn't use web3.js in this case.

Here's [some interesting relevant discussion](https://github.com/ethers-io/ethers.js/issues/427).  Looks like it might be relatively easy to add this functionality.  

Though I'm still wondering if we aren't off-base here.  At least one of the relevant errors in Sentry are specifically coming from within web3.

**Comment by tomlinton** [comment] 2019-09-18 23:07
Interesting, I'd hope ethers would throw on any non-success codes. I was thinking Alchemy might be returning something that looks like a success code but actually isn't (i.e. a 200 response on something that is an error with an error message in the response that needs to be parsed).

**Comment by micahalcorn** [comment] 2019-09-25 19:53
Closing until we get another report 🤞

**Closed by micahalcorn** 2019-09-25 19:53 UTC
Labels: P1, android, bug, dapp, transaction flow, ui/ux
