### ISSUE TITLE
Error on profile page

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2166] opened 2019-05-01 05:44 UTC
I get an error page when going to the profile page.
This is in production but I have seen similar issue on staging and dev.

Repro steps:
1. got to dapp
2. clear local storage
3. signup for origin reward
4. from campaign page, click on one of the attestation action
5. link goes to https://dapp.originprotocol.com/#/profile where I get blank page with error "Error! Please refresh the page". Clicking on Error shows a modal that says "TypeError: Cannot read property 'length' of undefined". No error show up in JS console.

**Comment by franckc** [comment] 2019-05-01 06:46
Mitigated by this bandaid that I committed and deployed to prod: https://github.com/OriginProtocol/origin/commit/d88b142c1f71264e2fa2a56ac18eabfa2e20ab51

Though I'd love for someone who understands react to tell me what the root cause is so that we can put in a better long-term fix... :)

**Comment by tomlinton** [comment] 2019-05-01 09:43
The issue is mostly [here](https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/src/hoc/withGrowthCampaign.js#L46-L58). That renders the wrapped component even when loading has not yet completed, so initially the `growthCampaigns` prop that gets passed will be undefined. It could be handled like [this](https://github.com/OriginProtocol/origin/blob/a8542d2ea7c9c0b6dbcc3d77d23d319701a79e6c/dapps/marketplace/src/components/GrowthCampaignBox.js#L139-L140) or how you've done it.

Thanks for figuring out the fix!

**Comment by franckc** [comment] 2019-05-01 16:03
ahhhh. you are so skilled in the React arts @tomlinton - thank you for enlightening me !

**Comment by micahalcorn** [comment] 2019-05-02 19:54
Resolved by #2170 ✅

**Closed by micahalcorn** 2019-05-02 19:54 UTC
Labels: P1, growth, identity
