### ISSUE TITLE
[Brave browser] Mainnet Beta for CryptoMerch: Twitter token not working

### ISSUE THREAD

**Issue by hashoshi** [OriginProtocol/origin#1590] opened 2019-03-04 20:06 UTC
When trying to verify Twitter for Origin profile, the app says "session not found" and Twitter dialog says that the token is expired. I suspect this is the API token on the Origin side. 

Steps to reproduce:
Log into Origin using metamask on Brave browser
Navigate to update profile page
Select add twitter
Log into Twitter on the popup
Select 'authorize' on Twitter
Error message occurs

If you need help, please ask in our [#engineering channel on Discord](http://www.originprotocol.com/discord).

We use issues for tracking features, bugs and discussions. Please make an attempt to confirm that your issue is not already filed. It's easy to do this using [our project board](https://github.com/orgs/OriginProtocol/projects/2).

**Comment by franckc** [comment] 2019-03-04 22:09
Thanks @hashoshi for reporting this issue.
We haven't fully qualified the Origin DApp on Brave browser. We expect there are issues, in particular it has been reported that some of the "shields" settings can break our DApp.

**Comment by micahalcorn** [comment] 2019-04-08 03:49
Considering this a duplicate of #1867 😬

**Closed by micahalcorn** 2019-04-08 03:49 UTC
Labels: bug, dapp
