### ISSUE TITLE
Publish button not greyed out for several seconds after publishing a profile

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1259] opened 2019-01-17 06:53 UTC
After a user clicks "Publish" and accepts the transaction in metamask, the Publish button is not greyed out until the block containing the transaction is mined. On Mainnet, this typically takes 15sec but can take longer.

During that period of time, the user does not get any feedback from the UI in terms of what's happening aside from the small spinner in the pending blockchain transaction dropdown. Therefore there is a significant risk the user would attempt to press Submit again, causing her to pay gas fees for a 2nd transaction.

We should grey out the Submit button as soon as the user hits Publish.

**Comment by tomlinton** [comment] 2019-01-17 19:17
Similarly the "Continue" button doesn't get greyed out for attestations so you can click it multiple times and end up with several codes being sent to your phone/email.

**Comment by micahalcorn** [comment] 2019-03-12 20:50
I'm not sure how much of the above is still true since moving to DApp2, but I have confirmed that the "Publish Now" button is enabled whether or not changes have been made to the profile. It should be disabled until provisional changes have been made that need to be published.

**Comment by micahalcorn** [comment] 2019-04-05 01:53
Related: #1729

**Comment by micahalcorn** [comment] 2019-04-10 22:48
Resolved by #2002 🤞

**Closed by micahalcorn** 2019-04-10 22:48 UTC
Labels: dapp, good first issue, identity, javascript, ui/ux
