### ISSUE TITLE
White Screen Of Death

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2983] opened 2019-08-15 21:45 UTC
There is a problem in _our_ mobile app that I thought was only happening in MetaMask's mobile app. Interestingly, I think it happens to _all_ DApps in theirs.

**Steps To Reproduce**
1. See listings in the marketplace tab
1. Get a push notification from some influencer on Instagram
1. Click the push notification
1. Be influenced
1. Reopen the Origin app
1. Authenticate
1. Be stuck on a white screen

**Video:** [Youtube video of a bug](https://www.youtube.com/watch?v=_g1m1vZOHAM)

Actually, I don't think you need to go through those steps. Just background the app and then open it again with a requirement to authenticate. It doesn't happen _every_ time, but it usually does.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by sparrowDom** [comment] 2019-08-16 14:50
I've done some debugging here, results are inconclusive unfortunately. I couldn't reproduce this problem on Android only IOS. It seems to me that the problem lies in `react-native-webview` implementation of react's wrapper in IOS. 

The error is reproducible even if we strip the functionality of our WebView to bare minimum: 
```
<WebView
  source={{ uri: this.state.webViewUrlTrigger }}
  onLoad={async () => {
    await this.props.setMarketplaceReady(true)
  }}
/>
```
only passing the source url and triggering a function when the marketplace loads. 

I have found it easiest to reproduce the by switching network type in the settings (from Mainnet to Rinkeby for example) and immediately after the switch exit the app and then re-enter it. Though reproducing this is sporadic for me. Sometimes it takes 20 tries sometimes 3. 

 Sometimes a blank screen is presented, sometimes a marketplace screen is frozen (with the previous marketplace address - when you switch to Rinkeby it stays stuck on Mainnet Dapp). I can scroll it up/down, but the buttons are non interact-able and after 150% screen height there is no more rendering. See picture: 

![unnamed (1)](https://user-images.githubusercontent.com/579910/63175163-bd226300-c043-11e9-9b22-16b7984307a8.png)

Below the listing with Matt the rendering is just cut. 
I suspect that the browser component somehow doesn't receive the message that it has regained focus and stays in some resource conserving / disabled state. As soon as I hook a Safari debugger to it, it wakes back up again. 

This is happening on both implementations of WebView: `WKWebView` and `UIWebView`

I suspect solving this one will require dwelling into `react-native-webView` sdk's IOS implementation.

**Comment by sparrowDom** [comment] 2019-08-16 15:59
Have reported as a [react-native-webView Github issue](https://github.com/react-native-community/react-native-webview/issues/786)

**Comment by sparrowDom** [comment] 2019-08-16 15:59
Have added a video link to the main issue description

**Comment by franckc** [comment] 2019-08-22 05:58
@sparrowDom We were discussing this issue during the eng meeting today. It is really a bad user experience on iOS right now :( Several of us hit that bug continuously while using the app heavily today. So a large number of users must also hit it, making it a high priority.

While we wait to hopefully hear back from the ReactNative team on the bug you filed, is there any short-term workaround that you can think of ? In the meeting it was mentioned that perhaps we could force the webview to refresh if the app comes back to forefront after being in the background ?

**Comment by tomlinton** [comment] 2019-08-22 08:05
If I remove the authentication prompt on restore from background I'm reasonably sure it'll fix it. We lose that functionality for a while but it is better than having this issue.

**Comment by micahalcorn** [comment] 2019-08-22 17:34
I like @tomlinton's suggestion while we wait for a webview fix. I was following Robinhood's lead on requiring it every time, but a lot of apps don't do that. Namely, Coinbase 🔓

**Comment by tomlinton** [comment] 2019-08-22 23:04
Fix up in #3072. Release is on TestFlight and pending on Play Store, will push them live later today unless I hear of any issues. Looks fine though!

**Comment by sparrowDom** [comment] 2019-08-23 00:39
Have also created a fix for this one https://github.com/OriginProtocol/origin/pull/3072/files 

Basically the same thing as @tomlinton did, with the added step, if Origin Wallet app is in the background for more than 120 seconds the app shall be restarted upon return. So we still have some security.

**Comment by tomlinton** [comment] 2019-08-23 00:48
Cool approach @sparrowDom! I didn't think of that. Great idea to have that suspend time variable so it doesn't do it on quick backgrounds for checking bridge emails etc.

I think we defer to @micahalcorn and his product gang here. I'd personally prefer the no restart option, as I guess this triggers the whole "Loading marketplace" bit. I (and I guess most people) rely on system wide phone locks anyway, so the per app authentication isn't a huge deal for me.

**Comment by micahalcorn** [comment] 2019-08-23 07:44
Works for me @tomlinton ✅

I'm fine with no restart (especially in the short term), but I'll pass the buck to @joshfraser and @matthewliu since there are security implications. Again, Coinbase doesn't seem to worry about it while Metamask does.

**Comment by sparrowDom** [comment] 2019-08-23 10:12
Nice idea for a fix @tomlinton , couldn't reproduce the "page stops mid-rendering" bug on Android either with your fix.

I would rather see we do it with a restart/password prompt. Checking apps on my phone, basically any application that deals with funds is password/biometrics locked. My banking app, Android/Apple Pay, confirming payed app download / in app purchases, Paypal and even Coinbase. Though Coinbase does not require biometrics for opening the app but before you send out a transaction (see the fingerprint icon in the middle of the screen): 
![Screenshot_20190823-115226](https://user-images.githubusercontent.com/579910/63585149-c315c800-c59e-11e9-94bb-a84166dcb977.jpg)

I remember there were times when in app purchases on Apple didn't require passwords. And a child got his fathers phone and made a 3-4k $ in app purchases in a game. Father sued Apple and won if I remember correctly. 

The main thing secondary biometrics prevent is that when you hand your phone to a friend / family member they can not mess with your finances.

**Comment by tomlinton** [comment] 2019-08-23 20:52
Fixed #3072.

**Closed by tomlinton** 2019-08-23 20:52 UTC
Labels: P1, bug, dapp, mobile, ui/ux

**Comment by sparrowDom** [comment] 2019-08-25 21:34
@micahalcorn @tomlinton @joshfraser just that we do not accidentally pass this... 

Is no one concerned about the potential security implications? Coinbase and Metamask both have biometrics (one on re-entry, the other on transaction confirmation). There is a [PR](https://github.com/OriginProtocol/origin/pull/3074) that also solves this albeit with restarting the application if user has left it for more than 2 minutes.

I am fine by leaving it as it is, just wanted to confirm it was a conscious decision.

**Comment by joshfraser** [comment] 2019-08-25 21:55
Let's compromise and make the forced refresh only kick in after an hour.

It's probably smart to force people to reauthenticate after some amount of time. But 2 minutes feels too short and I really don't want to interrupt people during a session. Sometimes moving funds can be a bit slow if you're waiting on an exchange or something.
