### ISSUE TITLE
Listener: Stopped processing/skipped event

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin#2338] opened 2019-05-24 20:27 UTC
Listener missed an event.  `IdentityUpdated` event for account `0x11fF89Cfe7340501c743474a3b0634EF50B8A008` in tx `0xb9469866953bfa16ec6dd1e5587515ba7d67c93777dd165497996723ae196128`.

When the listener was restarted(~10AM PST Thursday 5/23), it picked up a bunch of backlogged events, including this one.

Possibly related: #1972

**Comment by mikeshultz** [comment] 2019-05-24 20:29
CC @franckc

**Comment by franckc** [comment] 2019-05-24 21:00
The listener got deployed on Tuesday 2019-05-21 16:37:14 and I suspect it did not process **any** event until we did another deploy on Thu 2019-05-23 10:25:49 ...

**Comment by mikeshultz** [comment] 2019-05-25 02:42
Some highlights from doing log analysis: 

- Process re-started 2019-05-21T23:37:05 UTC
- Seeing lots of connection errors during migrations
- During the time the listener was defunct, absolutely nothing was returned for query for range (7806009, 7807564).  etherscan confirms that events exist for that latest block(amongst others in that range)  https://etherscan.io/tx/0xcc61aeccb5c10fe2397a922c88d29febcff53c44d6d930b9b7760688a188ce72#eventlog
- There's ZERO output from event-cache during this time, the only output at the time is the logs below
- JSON-RPC errors started showing up around 10:13UTC on 5/23 and stopped roughly a minute later. They appear to be handled just fine
- Listener restarted @ 2019-05-23T17:23:41 UTC, saw more PG connection errors, possibly a died process
- restarted almost immediately at 2019-05-23T17:25:40 with yet again, connection errors, but this time actually processed events. Also see pg connection errors during migrations processing

    event-listener: Processing from 7805973 for IdentityEvents
    event-listener: Querying events within interval (7805973, 7806196)
    event-listener: Got 0 new events for IdentityEvents
    event-listener: Processing from 7806009 for Marketplace
    event-listener: Querying events within interval (7806009, 7806196)
    event-listener: Got 0 new events for Marketplace

The far edge of the block range increases, so it is still aware of new block on the chain.

Will follow this up with some code analysis later to see if I can make sense of that defunct state as seen on 5/21.

**Comment by mikeshultz** [comment] 2019-05-25 02:54
Can't really say it's related, but does `npm run migrate` not exit with a non-zero exit code on connection failure?  Shouldn't it?  The docker `CMD` chains the commands: 

    CMD eval $(envkey-source) && \
        npm run migrate --prefix infra/discovery && \
      npm run migrate --prefix packages/event-cache && \
      npm run migrate --prefix infra/identity && \
      npm run start:listener --prefix infra/discovery

It's appears to me that the `ECONNREFUSED` @ `2019-05-21T23:37:09.783511340Z` occurred during process startup and not during migrations.

    [INFO] - 2019-05-21T23:37:09.443246299Z - 
    [INFO] - 2019-05-21T23:37:09.443293292Z - > @origin/discovery@0.1.0 start:listener /app/infra/discovery
    [INFO] - 2019-05-21T23:37:09.443300924Z - > per-env
    [INFO] - 2019-05-21T23:37:09.443305393Z - 
    [ERROR] - 2019-05-21T23:37:09.783511340Z - (node:121) UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
        at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:170:24)
        at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:174:14)
        at Connection.emit (events.js:189:13)
        at Connection.EventEmitter.emit (domain.js:441:20)
        at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:72:10)
        at Socket.emit (events.js:189:13)
        at Socket.EventEmitter.emit (domain.js:441:20)
        at emitErrorNT (internal/streams/destroy.js:82:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    [ERROR] - 2019-05-21T23:37:09.783668034Z - (node:121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    [ERROR] - 2019-05-21T23:37:09.783672895Z - (node:121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    [INFO] - 2019-05-21T23:37:09.824906825Z - 
    [INFO] - 2019-05-21T23:37:09.824968452Z - > @origin/discovery@0.1.0 start:listener:production /app/infra/discovery
    [INFO] - 2019-05-21T23:37:09.824976673Z - > node src/listener/listener.js
    [INFO] - 2019-05-21T23:37:09.824981953Z - 

Good chance this is the cause of the defunct state.  I think a container dependency might be in order, I guess between `event-listener` and `cloudsql-proxy`?

**Comment by mikeshultz** [comment] 2019-05-25 03:09
Also consider retries in Sequelize.  Seems limited by look into: 

- `options.retry` in Sequelize constructor http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html
- Peoples' comments on how they handled it: https://github.com/sequelize/sequelize/issues/2113
- A PR that adds retries to query(not sure if it affects connections) https://github.com/sequelize/sequelize/pull/8961

**Comment by franckc** [comment] 2019-05-27 05:25
Thanks @mikeshultz for analyzing those logs !
Indeed it does look something happened during startup related to the DB connection...

Now, if the DB connection was unusable, I would have expected the listener to exit its mainloop when calling the method [getLastBlock](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/listener.js#L145) since it does a DB access ?
But based on logs, the listener did not. We see logs from this [line](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/listener.js#L149)).
Another indication that the listener was able to successfully query the DB is that it resumed processing at blocks stored in the listener table rather than at default block from CONTINUE_BLOCK env var. See those 2 logs:
2019-05-21 16:37:15.611 PDT
[36;22m[DEBUG] [39;1mevent-listener[0m: Processing from 7805973 for IdentityEvents
2019-05-21 16:37:17.937 PDT
[36;22m[DEBUG] [39;1mevent-listener[0m: Processing from 7806009 for Marketplace

I did a quick test on my local by setting DATABASE_URL to an incorrect value. I got the ECONN_REFUSED error and the listener exited its main loop...

So overall I wonder if the DB error is a red-herring and if something else was going on ?
Was the infura node the listener querying somehow hosed and not returning any new event ?

**Comment by mikeshultz** [comment] 2019-05-27 05:49
> Was the infura node the listener querying somehow hosed and not returning any new event ?

That's entirely possible, but requires a lot of assumptions since their infra is nebulous.  The latest block was going up, but the websocket connection is likely to go to a completely separate system/node in Infura's backend(probably, *shrugs*).  There's [no incidents on status.infura.io](https://status.infura.io/), whatever that's worth.

That's a good point about the DB request in `getLastBlock`.  Eye-parsing the code now, but nothing has really jumped out at me yet.

**Comment by mikeshultz** [comment] 2019-05-27 07:06
What's really bugging me here is that there's nothing from event-cache during this error state.  

I'm wondering if it's actually the reverse.  The websocket died (or was feeding bad data) while the JSON-RPC requests were fine.  The listener uses `eth_getBlock` for it's computation of the block range, but event-cache is getting its latest block from the websocket configured in `graphql/src/contracts.js`.  The error handling on that looks okay, so if it was an error event, it should have been handled(unless there's a completely silent bug in web3.js).

Could also be related to `graphql-subscriptions` and `PubSub`.  No real clue what would happen if that died, I don't see any configured error handling.

I added PR #2347 that would at least show those `noop, current` messages in the case of the websocket not updating blocks for whatever reason.

**Comment by franckc** [comment] 2019-05-27 16:10
Thanks for adding that instrumentation. Yes, you are right it is odd there was not more logging from event-cache during that time...

Couple thoughts:
 - We are using a pretty old version of web3. I wonder if they have fixes in the more recent versions that would be relevant to this issue ? We had some regressions in various parts of our code last time we tried to upgrade so while I think we should definitely have a goal to upgrade, we should do it carefully, perhaps one service at a time.
 - Switching to Alchemy might help. Perhaps they are more stable than Infura. But to do that we have to figure #1986 . Though I have to say I have not tried to run the listener with Alchemy on local against Mainnet. I know listener hits that limit when running a backfill with concurrency mode turned on but not sure under normal operation if it does. Could be worth trying.

**Comment by micahalcorn** [comment] 2019-07-19 04:26
Closing this until we see it again 🤞

**Closed by micahalcorn** 2019-07-19 04:26 UTC
Labels: P2, bug, listener
