### ISSUE TITLE
[Notifications] Missing and non standardized data in the push_subscription DB table

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#872] opened 2018-11-02 16:58 UTC
While inspecting the data saved in the push_subscription DB table, I noticed the following:
- expiration_time column is not populated. Is that expected ? what is expiration_time for ? (I did not see it referenced in the server code).
- account are storing checksummed ETH addresses. I'd like to propose we standardize on using lowercase when saving any address in the DB. Otherwise I'm worried it will cause bugs in the future when doing lookups or comparison since some wallets do not use checksummed addresses.

Here is a snippet of data from the staging DB:
```
select id, expiration_time, account from push_subscription;
 id | expiration_time |                  account                   
----+-----------------+--------------------------------------------
  1 |                 | 0xce73904422880604e78591fD6c758B0D5106dD50
  2 |                 | 0xDFA4Ae049C94E193270aBE97964CdD1d9D291009
  3 |                 | 0x138eF43DA8F6C9c3a08aaE2509D296d1e0832666
(3 rows)

```

**Comment by franckc** [comment] 2018-11-02 16:59
@micahalcorn Pls lmk your thoughts on the above...

**Comment by micahalcorn** [comment] 2018-11-02 17:54
@franckc yes, expiration was intended to be null. I didn't think much about the consequence of adding the row without immediate plans to use it. 😐 I don't have an opinion on address case, but I certainly agree that we need a plan for it across the various apps in our repo. Don't we prefer checksum elsewhere?

**Comment by micahalcorn** [comment] 2018-11-05 14:06
You got it 🔡🔠

**Comment by franckc** [comment] 2019-04-24 21:44
@wanderingstan Are we going to continue using the push_subscription table moving forward ? If yes what do you think of normalizing eth addresses in there to lower case ?

**Comment by micahalcorn** [comment] 2019-05-01 21:05
Closing per @franckc & @wanderingstan 🙏

**Closed by micahalcorn** 2019-05-01 21:05 UTC
Labels: discussion, javascript, notifications
