### ISSUE TITLE
[Listener] Graphql sometimes returns stale data

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2163] opened 2019-04-30 23:18 UTC
Scenario:
 - User publishes phone attestation
 - listener processes an IdentityUpdated
 - listener queries Graphql to get Identity data and gets staled data back that does not include latest update

See these logs:
 - https://gist.github.com/franckc/47c4de05b92af64278e36ad11337de60
 - The phone attestation was part of IdentityUpdated event at block 922343
 - listener got the event which points to IPFS hash with latest identity that includes phone attestation: https://ipfs.dev.originprotocol.com/ipfs/QmWAL6GrhF136XkMHErGfVWu1nEy5guCaD1WbPiwr7JVym (this is 0x7438a2d7d5f4b9c319f280ed2a58c5c65aa3f5b92214c5f39d9440413cc08974 in bytes32)
 - logs show listener got staled data back from graphql that did not include the phone attestation

**Comment by franckc** [comment] 2019-04-30 23:18
CC @mikeshultz

**Comment by franckc** [comment] 2019-05-02 22:18
@mikeshultz Since you are knee deep in listener code, do you mind trying to figure this issue out ?
Having the listener producing reliable and correct data is going to be important for Origin.

Perhaps we could start with adding instrumentation and adding extra checks in the code ?
One idea could be to assert in the event-source code that we are processing event in order of block_number.

**Comment by mikeshultz** [comment] 2019-05-02 22:27
Yeah, I'm keeping an eye out.  I haven't yet been able to repro this with my trigger script yet.  So far it's been clean.

To organize my thoughts...

### What it (probably) isn't

- Signature validation issues (should output to logs)

### TODO

- Triple check sort in EventCache
- Verify DB attestation record (@franckc)
- Check if graphql currently outputs a valid record different from what is in the provided logs
- GraphQL caching?  Not seen in local dev, but worth considering

**Comment by franckc** [comment] 2019-05-02 22:33
Sounds like a good plan of attack to me !

**Comment by mikeshultz** [comment] 2019-05-06 15:36
Do we have the tx hash for this identity update?  Also, @franckc, can you get me the DB records for this user from `identity` and `attestation` for this user from the dev DB?

**Comment by franckc** [comment] 2019-05-06 16:20
I don't have the txHash handy... lmk if really necessary.
Here are the identity and attestation data:

```
origin=> select * from identity where eth_address='0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef';
                eth_address                 | first_name | last_name |           email           |    phone     | twitter | airbnb | facebook_verified |                         data                          |         created_at         |        updated_at         | google_verified | country | avatar_url 
--------------------------------------------+------------+-----------+---------------------------+--------------+---------+--------+-------------------+-------------------------------------------------------+----------------------------+---------------------------+-----------------+---------+------------
 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | Stan       | The Third | franck@originprotocol.com | 1 6507148740 | nick_p  |        | f                 | {"blockInfo": {"logIndex": 0, "blockNumber": 926715}} | 2019-04-23 18:51:00.046+00 | 2019-05-02 04:24:57.81+00 | t               | US      | 
(1 row)
```

```
origin=> select * from attestation where eth_address='0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef';
 id  | method  |                eth_address                 |           value           |                                                              signature                                                               |         created_at         | remote_ip_address 
-----+---------+--------------------------------------------+---------------------------+--------------------------------------------------------------------------------------------------------------------------------------+----------------------------+-------------------
 119 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0xa9f075e5ed42311a6324ab1bf67e22ad354626920c5713b2606f333886b08d5b1a1c62886a5e17911bf8ec7355e2d11dcd2808dbfeed8fe2d9035253f132dce31b | 2019-04-08 18:58:16.322078 | 205.209.24.227
 124 | PHONE   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | 1 4153206425              | 0x532c9192bf4dbd8cda7558b17fd42c769e56030f62594d6efa857eef8b03e8560544a20be86d324956d28f1bbf0031165e60a5382c1d3eef281162ac6d9353061c | 2019-04-08 19:33:48.614075 | 205.209.24.227
 140 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0x19dcaefbe64a912bb29672ea2f756ccded958a1c794bf755cda3622b932acbe62e41e4575bb4254b802906b7d11cfabc0e4a9c376d01f7dc97c3480d707e9ed01b | 2019-04-30 22:14:17.157147 | 136.24.109.2
 145 | PHONE   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | 1 6507148740              | 0x01c865730c0f7926f079ff2488b9ef560bb90d2022755be7e81b178ac28235e61953ede41164eadb37a9cbb3cb46f96829f7f9d0831bb0d894d3edeeb140e95b1c | 2019-05-01 06:15:42.718751 | 98.210.101.170
 115 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0xdba2ac7bfc7513bcc2c04b9955f46ca13e5ca247ea61d1456c57c6bb46d9637b607313eb786df1f1b790bb893c7060c0b9b33123ef3310bb62c4d2be1738aad21c | 2019-04-08 17:27:04.313596 | 205.209.24.227
 120 | PHONE   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | 1 4153206425              | 0x2b618e84f9d30157d7d667072ec668c2d14d482fc19feef178f91d1a0a57efa04cc76dc776a113a545ac17d590967bfac5326147db4d2e7cdc2e77f0ff78dbdc1b | 2019-04-08 19:03:19.842495 | 205.209.24.227
 125 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0x1f2d99abe42f73abacda0118edfe891296ac69ee81ec2d939c2b29e5a77192e526087e8a4c22d9760b8e2b698f7e49bf9f2669cf5bed664ff4a582c5653f14031b | 2019-04-09 14:50:02.919904 | 205.209.24.227
 130 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | stan@originprotocol.com   | 0x31edbc6d620546a883e642a338c6a35c43218fb2e336068c6bf1dda39f287eca37dda6320485a0089337314651f574d2ec67baa63f9c98c34ec00702a0466ea41b | 2019-04-23 18:38:42.940767 | 205.209.24.227
 141 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0x95a4beb1dd503ec09d9db2c6ee4f1842d25953d9d2fee4b474436ed19796df86293dda1be9b0965a042f82b4f50ab80d4e4fa5a7bfc2361d1180f041296602e91c | 2019-04-30 22:14:36.568324 | 136.24.109.2
 152 | GOOGLE  | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@domine.co.uk         | 0xe603352bc1ac9d750794817000e9834b80688ad6e6db602a1d24d3ca27cbd60406659e383826ffd5bbe04658de61f16e2579e98f3c375f37bec60c0963607ee91c | 2019-05-01 18:42:10.367566 | 136.24.109.2
 116 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0x9f86d987de9f228c81f8dda3c854118bcc9862cce7b355bdfcaf4b7347f2195b15aaaa9bfb6c27be0ac811b54e55e5e9239ba84924d99d1c80ff1e295e6727a21c | 2019-04-08 17:32:18.985674 | 205.209.24.227
 121 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0x59c66046da92f45795891aeadfb33eb4af775565e2ab6ceaf6a953ca8afe75011c1963a70a02da5d8528a7a90bef435ce45f81d4589268772be6142bda35aed71b | 2019-04-08 19:16:02.529832 | 205.209.24.227
 126 | PHONE   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | 1 4153206425              | 0xee5bc720a0228b47e6cbd12511a23b23c04c5f77506f113943eafe201a94d16c718fe44373d7aadbe68f18717bc8d6135447fbdc5d31d2133e2751e2c11f8f651b | 2019-04-09 14:50:51.086473 | 205.209.24.227
 142 | PHONE   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | 1 4153206425              | 0x447de7959c20cff6bf61dd045d1b96002785a221feeef24d1e96e793360b61ca2e29462f12dc4dc694aa028c02bef170e85ed3779677125caa28189be565adf21b | 2019-04-30 22:16:22.010454 | 136.24.109.2
 158 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0xd71a143f7dd8699bbe10bb75941e501f4a8537d5db5a97b1b0872a207a506ae65137685d3e656879906760da2cffe5ef27e9fa3078e11ea3a84c577811935cca1c | 2019-05-02 16:56:27.12346  | 136.24.109.2
 117 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0xf0a2a7756745d099c43bea16735f43e75a432eb95186aa4b45523cee50c8c22e26e9e4661a0ef3a4cf86a3ccd285021b3438f21388894a009bfd62bdc738d01d1b | 2019-04-08 17:33:08.513407 | 205.209.24.227
 122 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0x1c34f7603c161f14af0153de3ca92b4fce5f30dec09d82370836c21abb523f2e6f28e2b419b65b88a6f18f23b7f65e813aafda1dff9975a2857fedc161ca1e061b | 2019-04-08 19:30:39.774765 | 205.209.24.227
 148 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0x134d02dc1d8e46423a418b85bee66844a04c8764356529660dcf3e9a7b560dca7d9d340768fe7e04700724bd89cc5a47bbf8409b216b985aec9e6f412c0a90271c | 2019-05-01 15:46:15.436134 | 136.24.109.2
 149 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0xe1e388b436786b69af5cb53e05a3ca0c07f7050333864e44c8829fa6c603800b57f6f9abb19d7f7fec76fd55bbf3eeaee9a0a94e7a473eea498c4092310b2f481c | 2019-05-01 15:46:34.507662 | 136.24.109.2
 159 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0x89f212537d1a2d8add261281cafe8cb8964a1a646b462de1ebc8c9577143f36c727b76c0d3fd6e7d362476a5cdbd119fd966e6ce95a63894c14b93e4cd3e905a1c | 2019-05-02 16:57:39.799814 | 136.24.109.2
 118 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0xfd317d261fdb58c139740ee0a84c765869be4e04a4fb17b0339c0375ea809a301636ca2ad6f8b91b0681be2e74aa85a88af0c9926628698e831893c9be34ed311b | 2019-04-08 18:57:40.736608 | 205.209.24.227
 123 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick@poulden.com          | 0x317c278e8e46af592832a4a0b539f9b7ef3468f9f82a48557fd4e47b5906f2d6529d7628014a0f6fc2fe6c23f6ea1412eb85ef84d22676c7641b63e66253721b1c | 2019-04-08 19:32:34.603849 | 205.209.24.227
 144 | EMAIL   | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | franck@originprotocol.com | 0xd0b2f78b49b0f4aaa738fec4102b0d2e02b09f87a52902441052685bb48dc22f016a8e3ab97d9cd3f27ad3539b335ecf1bb780cbc86ed14eb07eaa455f87480c1b | 2019-05-01 06:15:15.280725 | 98.210.101.170
 160 | TWITTER | 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef | nick_p                    | 0x38085503773ad6de61a0d53bc6afeacba8445d4289f92c94b97bb969adf7ece32151a82e0160cba7b6d48ee3d1835ca5836c8287e4a3b4f15d0392f657a0b5641b | 2019-05-02 17:01:27.006023 | 136.24.109.2
(24 rows)

```

**Comment by mikeshultz** [comment] 2019-05-06 16:48
Here's the relevant TX:

    > eth.getTransaction('0x8f0060da0153fd5161c0f2d9881005a7f6a1631ce164a5b34648dd11b475b97d')
    {
      blockHash: "0x50ac7d4e76ed0401157e1af95d1dd0b201808bd4e0c061caca866b0256cf2c37",
      blockNumber: 922343,
      from: "0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef",
      gas: 30000,
      gasPrice: 1000000000,
      hash: "0x8f0060da0153fd5161c0f2d9881005a7f6a1631ce164a5b34648dd11b475b97d",
      input: "0xa30749df7438a2d7d5f4b9c319f280ed2a58c5c65aa3f5b92214c5f39d9440413cc08974",
      nonce: 4,
      r: "0xa8558cebf77e959a2233bcc25d550734882d0c36502371040dac8e4660c3cdaa",
      s: "0x7398cc935d146b3cb437134dbaeb5be3eec0255654f9cf676ecc576bf31d92f9",
      to: "0xe760d066bd8bbe22d7e9d8107be878102bd8d57d",
      transactionIndex: 0,
      v: "0x1180",
      value: 0
    }
    > eth.getTransactionReceipt('0x8f0060da0153fd5161c0f2d9881005a7f6a1631ce164a5b34648dd11b475b97d')
    {
      blockHash: "0x50ac7d4e76ed0401157e1af95d1dd0b201808bd4e0c061caca866b0256cf2c37",
      blockNumber: 922343,
      contractAddress: null,
      cumulativeGasUsed: 25029,
      from: "0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef",
      gasUsed: 25029,
      logs: [{
          address: "0xe760d066bd8bbe22d7e9d8107be878102bd8d57d",
          blockHash: "0x50ac7d4e76ed0401157e1af95d1dd0b201808bd4e0c061caca866b0256cf2c37",
          blockNumber: 922343,
          data: "0x7438a2d7d5f4b9c319f280ed2a58c5c65aa3f5b92214c5f39d9440413cc08974",
          logIndex: 0,
          removed: false,
          topics: ["0x8a49a94a170e0377e29de8e4b741993bed3dc902443fdc59d79e455137ecab18", "0x000000000000000000000000c5fdf4076b8f3a5357c5e395ab970b5b54098fef"],
          transactionHash: "0x8f0060da0153fd5161c0f2d9881005a7f6a1631ce164a5b34648dd11b475b97d",
          transactionIndex: 0
      }],
      logsBloom: "0x00000000000000000000010000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000080000000000000000000000000000000000000000002004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      root: "0x25669bce9a2a03f1f9769b5978e411e9c83319dee3bcca91896e74d2e68c4f5b",
      to: "0xe760d066bd8bbe22d7e9d8107be878102bd8d57d",
      transactionHash: "0x8f0060da0153fd5161c0f2d9881005a7f6a1631ce164a5b34648dd11b475b97d",
      transactionIndex: 0
    }

**Comment by mikeshultz** [comment] 2019-05-06 21:29
I suspect why the logs make no sense are because of [this block of code](https://github.com/OriginProtocol/origin/blob/master/infra/discovery/src/listener/handler_identity.js#L307-L309).  It may be leading us to believe that up-to-date IPFS data is being used when that's not what GraphQL is returning at all.  It's only a suspicion, but it's really the only thing that makes sense to me so far.

If I'm right, the root cause might be the same backend JSON-RPC node sync issues... In this case, both GraphQL and the listener use two separate instance of contracts, which in turn use separate instances of EventCache.  So while the instance in graphql might be getting lagged data, the listener has up to date data(or the other way around, too) causing unusual issues like the one reported here.

I'm not really sure what the best resolution of this issue might be yet.  Perhaps moving to a shared PostgreSQL backend for EC could help, but it would require some not-minor refactoring of how contracts are initialized in the listener, and graphql with the listener.

Before I jump into that, I'd rather see if this debug warning shows up in prod/staging/dev logs.

Ref: #2225

**Comment by franckc** [comment] 2019-05-06 22:36
Oh very interesting - I did not realize the contracts and listener are using 2 different event-cache.
That indeed could be a source of inconsistency.

**Comment by mikeshultz** [comment] 2019-05-06 23:13
After talking with @franckc, I confirmed that my multiple-instance-of-contracts assumption was wrong.  They're using the same instances, so it's **extremely** unlikely it's a node sync issue.  Franck also brought up the GraphQL cache (`apollo-cache-inmemory`), which looks like it could be a contender for causing this issue.  Not sure why I didn't see any caching in local testing, but will have a PR up to remove caching for the graphql client in the listener today.

**Comment by mikeshultz** [comment] 2019-05-07 19:19
Ref PR #2228

**Closed** 2019-05-17 04:46 UTC
Labels: P1, listener
