### ISSUE TITLE
Identity Found Or Not?

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2965] opened 2019-08-14 05:53 UTC
In MetaMask's mobile app, I see my picture in the top right corner but I still get "Hold on while we load your identity..." in the account drawer. This never seems to resolve itself no matter how long I wait. It is not accompanied by any errors in Sentry.

**Related**
If I click "Add a listing in the nav menu, I get an eternal spinner with the "Create a Listing" heading. But the "Your listing here" card leads to user activation.

_Partial Reproduction:_
1. Wait for identity to load
1. Toggle MetaMask to another account
1. Toggle back to account that previously had identity loaded
1. Get frustrated

***Note***: much of this happens often happens without doing the account dance.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by franckc** [comment] 2019-09-16 20:21
I just got that too on Android build v0.23.14
Account 0xD85A569F3C26f81070544451131c742283360400

CC @sparrowDom

**Comment by sparrowDom** [comment] 2019-10-02 19:28
@franckc @micahalcorn I can not reproduce this on latest Android build or Metamask App.

Can you see if it is still happening for you?

**Comment by franckc** [comment] 2019-10-02 22:37
Just tested and I'm unable to reproduce on android v0.25

**Comment by micahalcorn** [comment] 2019-10-03 01:31
Okay 🤞

**Comment by sparrowDom** [comment] 2019-10-03 21:36
I am reproducing / debugging this on 0.25 right now.

**Comment by sparrowDom** [comment] 2019-10-04 12:01
Sorry I have confused this ticket with another one. (my mind was on vacation) Ignore my last message closing this as done correctly by @micahalcorn

**Closed by sparrowDom** 2019-10-04 12:01 UTC
Labels: P2, bug, dapp, help wanted, identity, ui/ux
