### ISSUE TITLE
Enable Messaging not working

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#1437] opened 2019-02-08 13:22 UTC
on https://trips.origindapp.com/ (Creator)
Chrome os x 10.14.2
Eth: 0x36666e1fdC526f6df4638491F087e907A542BCdf

whenever I click on Enable messaging, nothing happens.
I've been trying since last night, cleared browser cache, closed and reopened browser.
In Console I get the attached errors.

![screenshot 2019-02-08 at 14 20 59](https://user-images.githubusercontent.com/34341206/52480750-e4880700-2bac-11e9-991c-84668c98c595.png)

**Comment by simibac** [comment] 2019-02-08 23:47
I can confirm that I have the same problem.

**Comment by micahalcorn** [comment] 2019-02-08 23:53
@Natasha08 I saw this locally yesterday with @crazybuster. We think that https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/components/compact-messages.js#L49 is being called infinitely for some reason. Can you check on this?

**Comment by letitcloud** [comment] 2019-02-13 17:45
same here.

**Comment by Natasha08** [comment] 2019-02-13 20:58
@micahalcorn Yea I'll have a look right after I get the PR for DApp2 listings search... Sorry just seeing this

**Comment by Natasha08** [comment] 2019-02-14 05:25
@micahalcorn @letitcloud I'm trying to reproduce this bug w/o success. Can you provide detailed steps for replication? I have tried to post back-to-back messages as a prospective buyer and as a buyer who has made an offer

**Comment by lucadgtrip** [comment] 2019-02-15 14:39
@Natasha08 I am trying to reproduce it but all I can say is that I'm clicking on the blue "Enable Messaging" button and nothing happens.
Both in https://dapp.originprotocol.com and https://trips.origindapp.com/
![screenshot 2019-02-15 at 16 36 47](https://user-images.githubusercontent.com/34341206/52863337-4661e700-3140-11e9-9be4-fa72370bd1cf.png)

**Comment by Natasha08** [comment] 2019-02-15 17:23
Thanks @lucadgtrip I'm getting that same problem as well now on https://dapp.originprotocol.com

**Comment by micahalcorn** [comment] 2019-02-15 18:28
@Natasha08 are you getting any errors in the console? There's no prompt waiting in MetaMask? I can't reproduce that.

**Comment by Natasha08** [comment] 2019-02-15 18:58
@micahalcorn zero errors in the console https://drive.google.com/file/d/1jKLu9wu1g5ypotb97ttRSu3ZVHzrSxQb/view?usp=sharing

**Comment by Natasha08** [comment] 2019-02-15 21:34
@micahalcorn I think the failing Enable Messaging button is related to the message cannot be decrypted issue. See https://drive.google.com/file/d/1IZAGIRzfjv8vJUWLgIPbGaR8wuB3SnfI/view?usp=sharing.

With regards to the `findPreviousMessage` issue, I cannot find a branch of logic that would cause the infinite loop. I still think that `componentDidUpdate` was being called and setting state, causing a re-render + a start over of the `findPreviousMessage` recursion. Maybe @crazybuster could pull down my branch and see if he still has the problem (since I still cannot reproduce it , even following @micahalcorn 's latest instructions on master 😞 ).

**More about [`findPreviousMessage`](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/components/compact-messages.js#L37)**
I thought I would explain what's going on in the component, so maybe someone will have a Eureka moment.

In the render, we are mapping over the `sortedMessages`. For each message in that map, we are calling `findPreviousMessage` to find the last user message (versus a transaction message). A user message has a `created` property, while a transaction message has a `timestamp` property.

If it is the first message in the collection, we do not run this `findPreviousMessage`. If during the recursion, we find ourselves at an `idx`(the current message's index) like -1, then we stop the recursion. If the message does not have a `timestamp` property or a `created` property, we return an empty object.

The recursion should only continue if we find that our message is a transaction message; and only in this case will `previousIdx` be defined. From my testing the recursion restarting (where `idx` is 1) is when `setState` is called in `componentDidUpdate`.

**Comment by micahalcorn** [comment] 2019-02-15 21:50
@Natasha08 I see that the button is ineffective while everything is still loading, but keep canceling it in the video. Doesn't everything work fine if you sign to enable messaging?

**Comment by Natasha08** [comment] 2019-02-15 22:00
@micahalcorn oh yea I should have shown that in the video. When you sign it, it works. I was just refreshing to show the failure again. Also, the first time I had this problem earlier today, I did not have any errors and the button remained unresponsive.

**Comment by micahalcorn** [comment] 2019-02-15 22:02
Basically, there's a race condition there that causes messages to not be decrypted initially, but it should be harmless. All of this will get resolved soon when we centralize the reading of messages.

**Comment by crazybuster** [comment] 2019-02-15 22:27
@Natasha08 I looked findPreviousMessage and yeah the parameters are a little strange(the first one is basically ignored and the second is actually only used on init), but I can't find a way that could infinite loop either. But I had seen this the function being called over and over again, upon messaging from a new purchase, perhaps there's another flow on top of it that's looping:(

**Comment by Natasha08** [comment] 2019-02-21 18:53
@micahalcorn so this is still a problem on staging/production?

**Comment by micahalcorn** [comment] 2019-02-21 19:11
@Natasha08 The problem that I'm aware of is not related to an infinite loop. As far as I can tell, it's a case of MetaMask just not showing the prompt or getting the call for some reason. 😕

**Comment by Natasha08** [comment] 2019-02-21 19:31
😢

**Comment by lucadgtrip** [comment] 2019-02-22 06:19
tested again, still not working

**Comment by joshfraser** [comment] 2019-02-22 06:28
We're hearing multiple reports of messaging not working. Sometimes it can be addressed by just waiting for a minute or two for the syncing in the background to finish. Sorry for the frustration. We're going to prioritize fixing this.

**Comment by alexjspears** [comment] 2019-02-22 16:44
@joshfraser this is true, I had to wait ~3 minutes then got a metamask authentication dialog pop up - it is working albeit slowly

**Comment by micahalcorn** [comment] 2019-02-22 23:53
I haven't quite had time to digest this and I have to run to a meeting, but I've identified part of the equation.

When someone clicks the button, [`startConversing`](https://github.com/OriginProtocol/origin/blob/bd562ea4533f2c1588ead919155eb16fb676e9ba/origin-js/src/resources/messaging.js#L246-L253) _**is**_ getting called. However, it's not calling `initKeys`, it's just [setting `convs_enabled`](https://github.com/OriginProtocol/origin/blob/bd562ea4533f2c1588ead919155eb16fb676e9ba/origin-js/src/resources/messaging.js#L251) because `ipfs_bound_account` has not yet been set. It's still [waiting for ipfs to be ready](https://github.com/OriginProtocol/origin/blob/bd562ea4533f2c1588ead919155eb16fb676e9ba/origin-js/src/resources/messaging.js#L389). And thus, we haven't asked MetaMask to do anything yet.

I'm still not clear on why the DApp is not aware that messaging has, in fact, already been enabled. I'll come back to it soon.

**Closed** 2019-02-23 04:03 UTC
Labels: bug, javascript, messaging, ui/ux

**Comment by micahalcorn** [comment] 2019-02-23 15:53
@lucadgtrip @alexjspears @letitcloud @simibac thanks for your reports. Please let us know if you still have this issue. 😁 Thanks!
