### ISSUE TITLE
T3 email template links not padded correctly

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#3874] opened 2019-11-06 02:26 UTC
See e.g.

![unnamed](https://user-images.githubusercontent.com/489202/68262964-a707ca00-00a9-11ea-8eb2-c64419b2c608.png)

**Comment by franckc** [comment] 2019-11-13 00:25
I'll look into this.

**Comment by franckc** [comment] 2019-11-13 23:33
I can't reproduce on gmail with Chrome (see screenshot below).

@tomlinton do you remember which email client you were using?

<img width="978" alt="Screen Shot 2019-11-13 at 3 32 26 PM" src="https://user-images.githubusercontent.com/945910/68813515-e3e43b80-062a-11ea-8eaf-6ab8676bf37a.png">

**Comment by tomlinton** [comment] 2019-11-13 23:34
I didn't experience this one personally, I believe it was @matthewliu?

**Comment by micahalcorn** [comment] 2019-11-14 17:16
While mobile isn't a priority, I know that the emails look less-than-desirable on small screens. That's probably the easiest way to reproduce any issues. 📲

**Comment by franckc** [comment] 2019-11-14 21:51
This should be fixed by the migration to use mjml as email template framework. See PR #3980

**Closed by franckc** 2019-11-14 21:51 UTC
Labels: P3, 𝕿𝟥
