### ISSUE TITLE
Generalized Partnership Referral Funnel

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#3948] opened 2019-11-11 22:38 UTC
We want to implement an onboarding funnel that shepherds users from another platform through app installation and Origin Rewards signup. Here are the steps that a user would experience:

1. See banner ad or link in partner marketing
1. Click partner referral link
1. See a dynamic landing page on originprotocol.com containing the relevant partner's logo and a call-to-action for downloading our app and earning the relevant amount of OGN ([design in progress](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5db1d9edc02f1e83271eb7bf))
1. If on mobile, click the one button that records partner attribution on the clipboard and points to either the App Store or Play Store; if on desktop, scan a QR code with a phone that points back to originprotocol.com in order to click a button that allows us to place attribution on the clipboard
1. Be routed to the appropriate app listing page in the App Store or Play Store
1. Click to install Origin Marketplace
1. Click to open Origin Marketplace
1. See our app open with the partner attribution silently read from the clipboard
1. Go through the standard native onboarding steps
1. See [a branded welcome screen](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5da7a86a3cd929655f883c25) (likely in the webview) that initiates Origin Rewards signup
1. Go through web-based user activation and Origin Rewards signup
1. See [an earned, partner-related reward in the dashboard](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5da7a86ab3a25017cb8939b9)

### Configurable Parameters

- Partner Name
- Partner Logo
- Logo size?
- OGN reward amount
- referral code

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by mikeshultz** [comment] 2019-11-12 18:39
> See our app open with the partner attribution silently read from the clipboard

I'm not really sure this is possible without permissions changes and code changes to our mobile app.  Also, writing to clipboard, at least on Chrome, may require requesting permissions(not silent).

Going to do some more research and see if I can put together a test to quickly confirm that this will or willn't work as designed.  Maybe see if I can come up with any alternatives as well.

**Comment by micahalcorn** [comment] 2019-11-12 20:14
@mikeshultz we will certainly need mobile app code changes, but I'm not aware of any permission requirements associated with the clipboard. 🤔

In addition to the requirements listed above, we want @coleman415 to be able to configure new instances of the _website_ landing page for prospective partners that he is talking to. He should be able to add a logo image to a directory along with a reward amount and some kind of unique identifier to a JSON file that is read to produce a landing page with a company's branding and associated OGN reward. This JSON file could also include some text and/or colors, but our current landing page design doesn't incorporate any partner-specific copy or styling. The only engineering involvement for him to share a new landing page with a prospective partner would be merging his PR and deploying the website.

As for deploying a fully-functional partner-specific funnel, we will need engineering intervention on DApp changes, possible custom styling, and updating the Origin Rewards rules.

**Comment by mikeshultz** [comment] 2019-11-12 20:31
I'm putting together the tests now to test this.  Looks like we can read with react-native just fine.  Not sure about in a webview but I doubt it(also probably not what we want).  Trying to figure out writing now.  Seems this isn't super consistent between browsers.  Will update when I know more.

**Comment by micahalcorn** [comment] 2019-11-12 20:40
I don't think we need to read from a webview and writing will require a click as described in 4️⃣ above.

**Comment by mikeshultz** [comment] 2019-11-12 21:21
For mobile, [react-native Clipboard](https://facebook.github.io/react-native/docs/clipboard.html) tested as working, no permissions required on Android(not sure about iOS).

[Support for the Clipboard API is weak](https://caniuse.com/#feat=mdn-api_clipboard) (`navigator.clipboard.writeText('text to write')`). Tested as working on Chrome and Firefox on Android(only works over HTTPS, local tests over HTTP will not work).   Looks like Safari or iOS browsers probably don't support this according to CanIUse.  [MDN seems unsure](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#Browser_compatibility) and I can't find a definitive source, nor do I have an iOS device for testing.

`document.execCommand() ` might be an option for safari but it requires selected text(think text input highlighted).

**Comment by micahalcorn** [comment] 2019-11-12 21:25
I think we should use a library like [copy-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard#browser-support) and not worry too much about it. 😕

**Comment by mikeshultz** [comment] 2019-11-12 21:28
I'm just leaving notes here.

**Comment by mikeshultz** [comment] 2019-11-14 20:23
@micahalcorn I added the "Configurable Parameters" section in your original post.  Can you edit it if it needs additions/removals?

**Comment by mikeshultz** [comment] 2019-11-15 22:35
@micahalcorn question above and also: 

- Will the reward amount be changing per partner or will it be fixed by campaign month?
- Are any of the designs final enough to start implementing?
- Do I just ping you/Aure via Zeplin for assets?

**Comment by micahalcorn** [comment] 2019-11-16 00:45
I think the config looks good @mikeshultz. The reward amount will potentially be different for various partnerships, which I think is included in the config (at least for the website). We're aware that the rules will need to be changed by engineering for it to actually take effect in the DApp and growth server. The designs should be good to go. 🚀

**Comment by mikeshultz** [comment] 2019-11-21 19:03
Relevant PRs:
https://github.com/OriginProtocol/origin-website/pull/445
https://github.com/OriginProtocol/origin/pull/3996

**Comment by mikeshultz** [comment] 2019-11-21 19:10
@micahalcorn so is 10 supposed to replace [this welcome page](https://shoporigin.com/#/welcome) or send users to it?

**Comment by micahalcorn** [comment] 2019-11-21 19:14
@mikeshultz it is for these users (and eventually those referred by friends), but we still want people to be able to navigate to the old welcome landing page. 👍

**Comment by mikeshultz** [comment] 2019-11-25 22:25
PR for the forced dapp onboarding: https://github.com/OriginProtocol/origin/pull/4055

Other than anything-that-comes-from-testing, the only outstanding task is that completed rewards are not displaying on the campaigns page.

**Closed** 2019-12-12 21:32 UTC
Labels: P1, dapp, html/css, javascript, mobile, ui/ux
