### ISSUE TITLE
Creating a listing fails

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#928] opened 2018-11-14 11:07 UTC
After the clicking `continue` on image cropper the DApp throws an error.

**PR that solves the problem**: https://github.com/OriginProtocol/origin/pull/882
<img width="1920" alt="screenshot 2018-11-14 12 05 36" src="https://user-images.githubusercontent.com/579910/48478834-be4d0800-e805-11e8-992d-02948e03bdba.png">
<img width="1920" alt="screenshot 2018-11-14 12 05 42" src="https://user-images.githubusercontent.com/579910/48478840-c016cb80-e805-11e8-862f-5c108208f36a.png">

**Comment by sparrowDom** [comment] 2018-11-14 11:08
@jordajm perhaps you know why this might happen?

**Comment by jordajm** [comment] 2018-11-14 16:51
I'm not totally sure what triggered this change - maybe an update to the `react-beautiful-dnd` library? But I have a fix for it here: https://github.com/OriginProtocol/origin/pull/882
Hopefully that PR will get merge this morning - if not I can pull out that fix and put it in a separate PR.

**Comment by sparrowDom** [comment] 2018-11-14 16:53
Nice! There is no rush, at least from my side.

**Comment by franckc** [comment] 2018-11-14 16:58
This is only happening on localhost and not in prod, correct @sparrowDom ?

**Comment by jordajm** [comment] 2018-11-14 17:02
I just confirmed that it is not happening on prod @franckc. I think it must be related to the latest release of the drag/drop library or something. We should be safe to wait for #882 to be merged.

**Comment by sparrowDom** [comment] 2018-11-14 17:03
yup @franckc like @jordajm says only on localhost

**Comment by franckc** [comment] 2018-11-14 20:05
Excellent. Thanks @jordajm @sparrowDom !

**Comment by franckc** [comment] 2018-11-14 20:11
Oh actually. So that means we need to deploy #882 to fix this... hmm.. that complicates things a bit :)
Because I was hoping to first test the performance mode in prod/staging (and that requires deploying master), before deploying #882.... Any chance we could put a quick fix for this issue in master ?

**Comment by jordajm** [comment] 2018-11-14 20:29
Yes, I'll put up a separate PR just for this fix

**Comment by jordajm** [comment] 2018-11-14 20:49
Here it is:
https://github.com/OriginProtocol/origin/pull/929

**Comment by jordajm** [comment] 2018-11-14 21:33
Resolved by https://github.com/OriginProtocol/origin/pull/929

**Closed by jordajm** 2018-11-14 21:33 UTC
Labels: bug, dapp
